name: new_proj
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  mqtt_client: ^10.3.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  pdf: ^3.11.1
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  printing: ^5.13.2
  fl_chart: ^0.69.0
  
  # Added for Alarm Notifications
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alarm_sound.mp3